# Generated by Django 5.2.8 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Velo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('type_velo', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=20)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('track', models.BooleanField(default=False)),
                ('demi_journee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('journee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emplacement', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='velos_images/')),
            ],
        ),
    ]
