# Generated by Django 5.2.8 on 2025-11-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('velos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('prix_neuf', models.FloatField()),
                ('kms_total', models.FloatField(default=0)),
                ('ca_total', models.FloatField(default=0)),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.velo')),
            ],
        ),
    ]
