# Generated by Django 5.2.8 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
