# Generated by Django 5.2.8 on 2025-11-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('velos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_location', models.CharField(choices=[('1/2 journée', '1/2 journée'), ('1 journée', '1 journée')], max_length=20)),
                ('nombre_participants', models.PositiveIntegerField()),
                ('taille', models.CharField(max_length=20)),
                ('circuit_prevu', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation_velo', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('clef', models.CharField(blank=True, max_length=50, null=True)),
                ('km_trajet', models.FloatField(blank=True, null=True)),
                ('guide', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.velo')),
            ],
        ),
    ]
