# Generated by Django 5.2.8 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('velos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_velos', models.IntegerField(default=1)),
                ('km_trajet', models.FloatField()),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('remarque', models.TextField(blank=True)),
                ('velos_utilises', models.ManyToManyField(to='velos.velo')),
            ],
        ),
    ]
