# Generated by Django 5.2.8 on 2025-11-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('velos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField()),
                ('semaine_fin', models.DateField()),
                ('parcours', models.CharField(blank=True, max_length=255)),
                ('ca', models.FloatField(default=0)),
                ('kms', models.FloatField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.velo')),
            ],
        ),
    ]
