# Generated by Django 5.2.8 on 2025-11-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_incident', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('service_concerne', models.CharField(blank=True, max_length=200)),
                ('decouvreur', models.CharField(blank=True, max_length=200)),
                ('action_interne', models.TextField(blank=True)),
                ('action_client', models.TextField(blank=True)),
                ('procedure_suivre', models.TextField(blank=True)),
                ('action_corrective', models.TextField(blank=True)),
                ('remarque', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
